Basic structure
ForceAwakenz/Enhanced-Task-App pull request #1
Opened 2021-12-08 12:32 UTC by ForceAwakenz

2021-12-08 13:14 UTC, sergey-rozhkov-andersenlab requested changes

2021-12-08 13:14 UTC, sergey-rozhkov-andersenlab commented on src/app/app-routing.module.ts
> +];
Выглядит что роутинг нам не нужен

2021-12-08 13:14 UTC, sergey-rozhkov-andersenlab commented on src/app/main/dock-test-sort/dock-test-sort.component.html
> +    </tr>
Черновой фаил? удаляй его не должно быть в проекте.

2021-12-08 13:14 UTC, sergey-rozhkov-andersenlab commented on src/app/main/dock-test-sort/dock-test-sort.component.spec.ts
> +    expect(component).toBeTruthy();
черновой? удаляй

2021-12-08 13:14 UTC, sergey-rozhkov-andersenlab commented on src/app/main/dock-test-sort/dock-test-sort.component.ts
> + * @title Sorting overview
Черновой? удаляй

2021-12-08 13:14 UTC, sergey-rozhkov-andersenlab commented on src/app/main/dock-test/dock-test.component.html
> +    </ng-container>
файл выглядит не нужным.

2021-12-08 13:14 UTC, sergey-rozhkov-andersenlab commented on src/app/main/main.module.ts
> +    MatToolbarModule,
Подключай только то что тебе необходимо, незачем лишнее тянуть.

2021-12-08 13:14 UTC, sergey-rozhkov-andersenlab commented on src/app/main/task-input/task-input.component.html
> +    (click)="isAddTaskClicked = true"
Для обработки лучше используй фунции

2021-12-08 13:14 UTC, sergey-rozhkov-andersenlab commented on src/app/main/task-input/task-input.component.html
> +            <input #taskInput matInput placeholder="Enter the task here" formControlName="taskTextInput">
зачем тебе ссылка на этот инпут taskInput?

2021-12-08 13:14 UTC, sergey-rozhkov-andersenlab commented on src/app/main/task-input/task-input.component.html
> +            <input matInput [matDatepicker]="picker" formControlName="taskDatePicker" #datePicker>
тоже самое datePicker

2021-12-08 13:14 UTC, sergey-rozhkov-andersenlab commented on src/app/main/task-input/task-input.component.ts
> +  @ViewChild('datePicker') datePicker!: ElementRef;
Тебе это не надо если ты используешь реактивные формы

2021-12-08 13:14 UTC, sergey-rozhkov-andersenlab commented on src/app/main/task-input/task-input.component.ts
> +    }
добавь валидация на форму. И просто проверя валидна ли форма

2021-12-08 13:14 UTC, sergey-rozhkov-andersenlab commented on src/app/main/task-input/task-input.component.ts
> +    this.datePicker.nativeElement.value = '';
Используй методы работы с реактивными формами. .setValue

2021-12-08 13:14 UTC, sergey-rozhkov-andersenlab commented on src/app/main/task-input/task-input.component.ts
> +    console.dir(this.datePicker.nativeElement);
Должно быть хорошое обоснование чтобы консоль лог отправлять в продакшен.

2021-12-08 13:14 UTC, sergey-rozhkov-andersenlab commented on src/app/main/task-list/task-list.component.html
> +        [ngClass]="{'doneTask': row.isDone ? 'line-through' : '' }">
[ngClass]="{'doneTask': row.isDone ? 'line-through' : '' }

Зачем тут тернарник?
лучше используй
[class.doneTask]="row.isDone"

2021-12-08 13:14 UTC, sergey-rozhkov-andersenlab commented on src/app/main/task-list/task-list.component.ts
> +}
Если такое скорее всего может переисползовать создавай фаил util и переноси туда.

2021-12-08 13:14 UTC, sergey-rozhkov-andersenlab commented on src/app/main/task-list/task-list.component.ts
> +  }
Для чего останавливаешь всплытие?

2021-12-08 13:14 UTC, sergey-rozhkov-andersenlab commented on src/app/main/task-list/task-list.component.ts
> +    event.stopPropagation();
Для чего останавливаешь всплытие?

2021-12-08 13:14 UTC, sergey-rozhkov-andersenlab commented on src/app/main/toolbar/toolbar.component.ts
> +  }
Выглядит так как этот кусок кода не работает, Не вижу подписки на то что возвращается в ngInit. 
Но если тебе надо такое его стоит переделать. `searchPhraze` на сабджект и next прокидывать в нее.

2021-12-08 13:14 UTC, sergey-rozhkov-andersenlab commented on src/app/shared/services/filter-input.service.ts
> +
Стоит использовать сабджект или бехевиар сабджект

2021-12-08 13:14 UTC, sergey-rozhkov-andersenlab commented on src/app/shared/services/task-data.service.ts
> +    return this.taskList$.asObservable().pipe(
Для чего приводишь в asObservable?
цепочка pipe автоматически веренет обзервбл

2021-12-08 13:14 UTC, sergey-rozhkov-andersenlab commented on src/app/shared/services/task-data.service.ts
> +  }
Логика сохранения в стор выглядит одинаковой. Возможно ее стоит вынести в отдельную функцию

taskList - магическая переменная. Вынеси ее в константу

2021-12-08 13:14 UTC, sergey-rozhkov-andersenlab commented on src/app/main/task-list/task-list.component.ts
> +import { TaskDataService } from 'src/app/shared/services/task-data.service';
Похоже IDE у тебя вставляет абсолютные пути, лучше использовать отнасительный

2021-12-08 13:14 UTC, sergey-rozhkov-andersenlab commented on src/app/main/task-input/task-input.component.ts
> +        id: +(new Date())}
Излишняя информация, это футренние штуки которые не должны быть интересны для добавления задачи, И уже в методе addTask эти поля добавляются. Инкапсуляция.

2021-12-08 15:10 UTC, ForceAwakenz commented on src/app/app-routing.module.ts
> +];
да, это то, что я с доков Ангуляра копировал. Уже все почистил.

2021-12-08 15:12 UTC, ForceAwakenz commented on src/app/main/dock-test-sort/dock-test-sort.component.html
> +    </tr>
удалил весь компонент

2021-12-08 15:12 UTC, ForceAwakenz commented on src/app/main/dock-test-sort/dock-test-sort.component.spec.ts
> +    expect(component).toBeTruthy();
удалил весь компонент

2021-12-08 15:12 UTC, ForceAwakenz commented on src/app/main/dock-test/dock-test.component.html
> +    </ng-container>
удалил весь компонент

2021-12-08 15:12 UTC, ForceAwakenz commented on src/app/main/dock-test-sort/dock-test-sort.component.ts
> + * @title Sorting overview
удалил весь компонент

2021-12-08 16:34 UTC, ForceAwakenz commented on src/app/main/main.module.ts
> +    MatToolbarModule,
сделал)

2021-12-08 16:34 UTC, ForceAwakenz commented on src/app/main/task-input/task-input.component.html
> +    (click)="isAddTaskClicked = true"
сделал

2021-12-08 16:47 UTC, ForceAwakenz commented on src/app/main/task-input/task-input.component.html
> +            <input #taskInput matInput placeholder="Enter the task here" formControlName="taskTextInput">
чтоб очистить поле после сабмита

2021-12-08 16:47 UTC, ForceAwakenz commented on src/app/main/task-input/task-input.component.html
> +            <input matInput [matDatepicker]="picker" formControlName="taskDatePicker" #datePicker>
чтоб очистить поле после сабмита

2021-12-08 16:52 UTC, ForceAwakenz commented on src/app/main/task-input/task-input.component.ts
> +  @ViewChild('datePicker') datePicker!: ElementRef;
хм, да, нашел метод reset у рекативных форм. Переделал.

2021-12-08 17:03 UTC, ForceAwakenz commented on src/app/main/task-input/task-input.component.ts
> +    this.datePicker.nativeElement.value = '';
я сделал через reset()

2021-12-08 17:05 UTC, ForceAwakenz commented on src/app/main/task-input/task-input.component.ts
> +    console.dir(this.datePicker.nativeElement);
да, я после ПРа сразу заметил и почистил, но ты успел проверить)

2021-12-08 17:14 UTC, ForceAwakenz commented on src/app/main/task-list/task-list.component.ts
> +}
я хотел тебя спросить. Так было в доках, поэтому я оставил так. Если причина может быть в переиспользовании - то, думаю, для этого приложения лучше в класс добавить, потому что вряд ли будет переиспользоваться.

Добавил в класс.

2021-12-08 17:19 UTC, ForceAwakenz commented on src/app/main/task-list/task-list.component.ts
> +  }
когда я нажимаю на чекбокс, он инвертирует переменную isDone, то же самое делает и клик по самому такску, поэтому при клике на чекбокс, если не останавливать всплытие, ничего не происходит

2021-12-08 17:21 UTC, ForceAwakenz commented on src/app/main/task-list/task-list.component.ts
> +    event.stopPropagation();
здесь можно не останавливать, но тогда перед удалением у задания поменяется статус isDone на противоположный. И если я захочу в это приложение дописать отслеживание истории заметок, то там все время будет некорректные данные.

2021-12-08 17:43 UTC, ForceAwakenz commented on src/app/shared/services/task-data.service.ts
> +  }
переделал

2021-12-09 09:37 UTC, ForceAwakenz commented on src/app/main/task-list/task-list.component.ts
> +import { TaskDataService } from 'src/app/shared/services/task-data.service';
готово, через tsconfig вывел пути @app и @src

2021-12-09 09:51 UTC, ForceAwakenz commented on src/app/main/task-list/task-list.component.ts
> +import { TaskDataService } from 'src/app/shared/services/task-data.service';
... ммм, кажется я все сломал, буду откатывать назад

2021-12-09 09:57 UTC, ForceAwakenz commented on src/app/main/task-list/task-list.component.ts
> +import { TaskDataService } from 'src/app/shared/services/task-data.service';
а так норм?
'../../../app/shared/services/filter-input.service'

2021-12-09 10:02 UTC, ForceAwakenz commented on src/app/main/task-input/task-input.component.ts
> +    }
Добавил, так намного лучше)

2021-12-09 10:08 UTC, ForceAwakenz commented on src/app/main/task-list/task-list.component.html
> +        [ngClass]="{'doneTask': row.isDone ? 'line-through' : '' }">
да, что-то я усложнил. переделал)

2021-12-09 10:51 UTC, ForceAwakenz commented on src/app/main/task-input/task-input.component.ts
> +        id: +(new Date())}
создал отдельный сервис для проверки и форматирования таски, реализовал проверку через геттер и сеттрер, это норм?

2021-12-09 11:21 UTC, ForceAwakenz commented on src/app/main/toolbar/toolbar.component.ts
> +  }
это странным образом работало, но переделал)

2021-12-09 11:21 UTC, ForceAwakenz commented on src/app/shared/services/filter-input.service.ts
> +
сделал

2021-12-09 11:44 UTC, ForceAwakenz commented on src/app/shared/services/task-data.service.ts
> +    return this.taskList$.asObservable().pipe(
хм, да. точно! переделал

2021-12-09 12:03 UTC, sergey-rozhkov-andersenlab requested changes

2021-12-09 12:03 UTC, sergey-rozhkov-andersenlab commented on src/app/app-routing.module.ts
> +];
Роутинг излишен для проекта.

2021-12-09 12:03 UTC, sergey-rozhkov-andersenlab commented on src/app/main/task-input/task-input.component.html
> +            <input #taskInput matInput placeholder="Enter the task here" formControlName="taskTextInput">
taskInput Она тебе не нужна

2021-12-09 12:03 UTC, sergey-rozhkov-andersenlab commented on src/app/main/task-input/task-input.component.html
> +            <input matInput [matDatepicker]="picker" formControlName="taskDatePicker" #datePicker>
Она не нужна

2021-12-09 12:03 UTC, sergey-rozhkov-andersenlab commented on src/app/main/task-input/task-input.component.ts
> +  @ViewChild('taskForm') taskForm!: FormGroupDirective;
taskForm тебе не надо, посмотри как работать с реативными формами

2021-12-09 12:03 UTC, sergey-rozhkov-andersenlab commented on src/app/main/task-input/task-input.component.ts
> +      };
Не, так не надо.

2021-12-09 12:03 UTC, sergey-rozhkov-andersenlab commented on src/app/main/task-input/task-input.component.ts
> +    this.taskDataService.addTask(this.formatTaskService.checkedTask);
Тут в функцию передаешь два параметра. И в функции уже собираешь задачу со всеми необходимыми полями.

2021-12-09 12:03 UTC, sergey-rozhkov-andersenlab commented on src/app/main/task-input/task-input.component.ts
> +    this.formatTaskService.checkedTask =
Также нехватает проверки на валидность формы.

2021-12-09 12:03 UTC, sergey-rozhkov-andersenlab commented on src/app/main/task-list/task-list.component.ts
> +  }
Это скорее функция не для класса. Потому что на каждый экземпляр класса она будет создаваться, Это скорее утилка. У тебя было верно что ты ее вынес в функцию, была бы большая вероятность что у тебя будучи в проекте по больше она будет переиспользовать и поэтому ее стоит выносить в утилки.

2021-12-09 12:03 UTC, sergey-rozhkov-andersenlab commented on src/app/shared/services/filter-input.service.ts
> +  // }
Удаляй, подобного не должно быть без обоснования

2021-12-09 12:03 UTC, sergey-rozhkov-andersenlab commented on src/app/shared/services/format-task.service.ts
> +}
Выглядит не нужным

2021-12-09 12:04 UTC, sergey-rozhkov-andersenlab commented on src/app/app-routing.module.ts
> +];
Не все удалил

2021-12-09 12:05 UTC, sergey-rozhkov-andersenlab commented on src/app/main/dock-test-sort/dock-test-sort.component.html
> +    </tr>
DONE

2021-12-09 12:05 UTC, sergey-rozhkov-andersenlab commented on src/app/main/dock-test-sort/dock-test-sort.component.spec.ts
> +    expect(component).toBeTruthy();
DONE

2021-12-09 12:05 UTC, sergey-rozhkov-andersenlab commented on src/app/main/dock-test-sort/dock-test-sort.component.ts
> + * @title Sorting overview
DONE

2021-12-09 12:05 UTC, sergey-rozhkov-andersenlab commented on src/app/main/dock-test/dock-test.component.html
> +    </ng-container>
DONE

2021-12-09 12:05 UTC, sergey-rozhkov-andersenlab commented on src/app/main/main.module.ts
> +    MatToolbarModule,
DONE

2021-12-09 12:05 UTC, sergey-rozhkov-andersenlab commented on src/app/main/task-input/task-input.component.html
> +    (click)="isAddTaskClicked = true"
DONE

2021-12-09 14:21 UTC, ForceAwakenz commented on src/app/app-routing.module.ts
> +];
Теперь все)

2021-12-09 14:23 UTC, ForceAwakenz commented on src/app/main/task-input/task-input.component.html
> +            <input #taskInput matInput placeholder="Enter the task here" formControlName="taskTextInput">
Мы решили оставить

2021-12-09 14:23 UTC, ForceAwakenz commented on src/app/main/task-input/task-input.component.html
> +            <input matInput [matDatepicker]="picker" formControlName="taskDatePicker" #datePicker>
пофиксил

2021-12-09 14:44 UTC, ForceAwakenz commented on src/app/app-routing.module.ts
> +];
удалил

2021-12-09 14:45 UTC, ForceAwakenz commented on src/app/main/task-input/task-input.component.ts
> +  @ViewChild('taskForm') taskForm!: FormGroupDirective;
инпуты удалил, с формы мы сошлись на том, чтоб оставить

2021-12-09 14:45 UTC, ForceAwakenz commented on src/app/main/task-input/task-input.component.ts
> +      };
переделал

2021-12-09 14:45 UTC, ForceAwakenz commented on src/app/main/task-input/task-input.component.ts
> +    this.taskDataService.addTask(this.formatTaskService.checkedTask);
переделал

2021-12-09 14:47 UTC, ForceAwakenz commented on src/app/main/task-list/task-list.component.ts
> +  }
вынес в утилки

2021-12-09 14:48 UTC, ForceAwakenz commented on src/app/main/task-input/task-input.component.ts
> +    this.formatTaskService.checkedTask =
выше есть валидатор

2021-12-09 14:51 UTC, ForceAwakenz commented on src/app/shared/services/filter-input.service.ts
> +  // }
удалил

2021-12-09 14:51 UTC, ForceAwakenz commented on src/app/shared/services/format-task.service.ts
> +}
да, все переделал

2022-01-03 09:40 UTC, merged